# Generated by Django 6.0.3 on 2026-03-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('datafile', models.CharField(default='text', max_length=255)),
            ],
        ),
    ]
