# Generated by Django 6.0.3 on 2026-03-22 10:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_datafile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='nick',
            field=models.CharField(default=api.models.generate_random_nick, max_length=50),
        ),
    ]
