# Generated by Django 6.0.3 on 2026-03-27 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studyupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('value', models.FloatField()),
                ('score', models.FloatField()),
                ('activity_status', models.CharField(max_length=64)),
                ('flag', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.studyupload')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'indexes': [models.Index(fields=['external_id'], name='api_studyre_externa_63fcdb_idx'), models.Index(fields=['created_at'], name='api_studyre_created_feec06_idx')],
            },
        ),
    ]
