services:
  - type: web
    name: paw-backend
    runtime: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.2"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: NEON_URI
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
